# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
        exclude: '.*\.fits$'
    -   id: end-of-file-fixer
        exclude_types: [csv]
        exclude: '.*\.fits$'
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/kynan/nbstripout
    rev: 0.6.1
    hooks:
    -   id: nbstripout
        args: ["--extra-keys=metadata.kernelspec metadata.language_info.version metadata.toc metadata.language_info.codemirror_mode.version metadata.language_info.pygments_lexer metadata.notify_time metadata.varInspector metadata.colab cell.metadata.colab cell.metadata.colab_type cell.metadata.outputId cell.metadata.id"]
