repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
        exclude: \.svg$
-   repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
    -   id: flake8
        exclude: seaborn/(cm\.py|external/)
        types: [file, python]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.971
    hooks:
     -  id: mypy
        args: [--follow-imports=skip]
        files: seaborn/_(core|marks|stats)/
